# Generated by Django 3.2 on 2021-06-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_myhelp_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessages',
            name='app_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.myappointment'),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_to',
            field=models.IntegerField(),
        ),
    ]
