# Generated by Django 3.2 on 2021-06-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20210608_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydisease',
            name='dise_url',
        ),
        migrations.AddField(
            model_name='mydisease',
            name='appointment_id',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='myapp.myappointment'),
            preserve_default=False,
        ),
    ]
